
! Example macro

res 'c:\dev\HandbookOfOpticalSystems\Vol04\hos_vol4_design_files_v2\Misc\45-1_Relay-system-achromat.otx'
FIE LSA
gra bmp fil 'C:\dev\HandbookOfOpticalSystems\Vol04\Ch45\figs\fig45p1PreOptimize.bmp'
gra t
DEL VAR ALL 
VAR s0 THI 
VAR s3 THI
TAR MAG = -1.0
TAR LAY f1 w2 = 0
OPT
FIE LSA
gra bmp fil 'C:\dev\HandbookOfOpticalSystems\Vol04\Ch45\figs\fig45p1PostOptimize.bmp'
gra t
vie
LIS